image: ubuntu:18.04

stages:
    - test

before_script:
  - apt-get update && apt-get install -y curl gnupg2 lsb-release software-properties-common git
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
  - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - apt-get update && apt-get install -y terraform=0.12.29

test_terraform:
  stage: test
  script:
    - cp ci_backend.tf ./google/backend.tf
    - cd google
    - >
      gpg --batch --yes --passphrase="$PASS_PHRASE"
      --output github_credential.json 
      --decrypt github_credential.json.gpg
    - |
      cat <<EOF >terraform.tfvars
      project_id           = "$PROJECT_ID"
      bastion_members      = $BASTION_MEMBERS
      ip_source_ranges_ssh = $IP_SOURCE_RANGES_SSH
      cluster_name         = "$CLUSTER_NAME"
      cred_file            = "github_credential.json"
      EOF
    - terraform init -input=false
    - terraform plan -out tfapply -var-file terraform.tfvars
