version: 2.1

workflows:
  plan_apply:
    jobs:
      - create_tfvars:
          context: GCP 
      - plan_apply:
          requires:
            - create_tfvars

jobs:
  create_tfvars:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - run:
          name: Decrypt gcp credentials
          command: |
            pwd
            gpg --quiet --batch --yes -d --passphrase="$PASS_PHRASE" \
            -o ./google/github_credential.json ./google/github_credential.json.gpg
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: google
          # Must be relative path from root
          paths:
            - google
    
  plan_apply:
    docker:
      - image: hashicorp/terraform:0.12.29
    steps:
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run:
          name: create terraform.tfvars
          command: |
            pwd
            cat \<<EOF >terraform.tfvars
            project_id           = "$PROJECT_ID"
            bastion_members      = $BASTION_MEMBERS
            ip_source_ranges_ssh = $IP_SOURCE_RANGES_SSH
            cluster_name         = "$CLUSTER_NAME"
            cred_file            = "github_credential.json"
            EOF
            ls -l

      - run:
          name: terraform init & plan
          command: |
            pwd
            ls -l
            terraform init -input=false
            terraform plan -out tfapply -var-file terraform.tfvars