apiVersion: v1
kind: Service
metadata:
  name: bee-api-service
  labels:
    service: bee-api
    environment: development
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: bee-api
  type: LoadBalancer
